# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c0a7c9987e36e23d7f17cca47c82f759d73506ad970b547fa35ebf5bf3f2c12b1ff5d3aa7797a177b911fdfb686a4f56472d17f408eaeb42d4880a744b65974

test:
  secret_key_base: b5284a20d0457086d457dda7d7cb22251709d2f13a47b5cbbdaa6ebd0b4616662f611d324f38e4a31952835a0b2a7fc2cac63a44e46b7432414407e1be95b142

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
